services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE:      "${DB_DATABASE}"
      MYSQL_USER:          "${DB_USERNAME}"
      MYSQL_PASSWORD:      "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    networks: [jupiter-net]

  web:
    image: dev.kimidev.com/kimicom/jupitermeetpro-docker/web-artisan:1.8.6-artisan-fx
    restart: unless-stopped
    ports:
      - "3000:80"                       # host:container
    volumes:
      - ./jupitermeet_pro/.env:/var/www/html/.env:ro
      - jupitermeet_storage:/var/www/html/storage
    # NO command override here!  Let the image’s ENTRYPOINT start Apache.
    depends_on:
      - db
    networks:
      - jupiter-net

  node:
    image: dev.kimidev.com/kimicom/jupitermeetpro-docker/node:1.8.6-prod
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "${RTC_MIN_PORT}-${RTC_MAX_PORT}:${RTC_MIN_PORT}-${RTC_MAX_PORT}/udp"
    volumes:
      - ./jupitermeet_pro/server/.env:/app/.env:ro
    command: ["npm", "run", "local"]   # HTTP-only mode
    depends_on:
      - db
    networks:
      - jupiter-net

networks:
  jupiter-net:
    driver: bridge

volumes:
  db_data:
  jupitermeet_storage:
