services:
  db:
    image: mysql:8.3
    container_name: jupitermeet-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: jupitermeet
      MYSQL_USER: jmuser
      MYSQL_PASSWORD: jmpass
    volumes: [db_data:/var/lib/mysql]

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports: ["3000:80"]

  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "9000:9000"
      - "${RTC_MIN_PORT}-${RTC_MAX_PORT}:${RTC_MIN_PORT}-${RTC_MAX_PORT}/udp"

networks:
  default:
    driver: bridge

volumes:
  db_data:
